name: "run tests"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ develop ]

concurrency:
  group: ci-dev-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-dev-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 21.4.0
      - name: Install dependencies
        run: cd backend && npm install
      - name: Run tests
        run: cd backend && npm run test